-- Tablas nuevas para control de alumnos y tiempos de vuelta.
-- No usa ninguna tabla preexistente.

create extension if not exists pgcrypto;

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  full_name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.lap_times (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  elapsed_ms integer not null check (elapsed_ms >= 0),
  recorded_at timestamptz not null default now()
);

create index if not exists lap_times_student_id_idx on public.lap_times(student_id);
create index if not exists lap_times_recorded_at_idx on public.lap_times(recorded_at desc);

alter table public.students enable row level security;
alter table public.lap_times enable row level security;

-- Politicas abiertas para prototipo con anon key en frontend.
-- Recomendacion: restringir por autenticacion cuando tengas login.
drop policy if exists "students_select" on public.students;
create policy "students_select"
  on public.students
  for select
  to anon, authenticated
  using (true);

drop policy if exists "students_insert" on public.students;
create policy "students_insert"
  on public.students
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "lap_times_select" on public.lap_times;
create policy "lap_times_select"
  on public.lap_times
  for select
  to anon, authenticated
  using (true);

drop policy if exists "lap_times_insert" on public.lap_times;
create policy "lap_times_insert"
  on public.lap_times
  for insert
  to anon, authenticated
  with check (true);
